### ISSUE TITLE
Compile error - unknown type name 'pid_t'

### ISSUE THREAD

**Issue by jsavage** [silentbicycle/mqtt_demo#1]
Hi, 
I am attempting to learn about mosquitto by following in your article at http://spin.atomicobject.com/2014/03/19/mqtt-protocol-ethernet/ . Thanks for making this available.

Anyway, I cloned your repository for mqtt_demo, ran make and found that mosquitto.h was needed which did not apear to be present on my system despite having installed mosquitto and mosquitto-client from the mosquito_ppa. So I uninstalled mosquitto and reinstalled mosquitto-1.4 from source.  Now when I try and compile the demo I am getting the following error which I have not as yet been able to resolve with my limited knowledge of c.

```
~/mqtt_demo$ make
cc -std=c99 -g -O3 -Wall    -c -o client.o client.c
client.c:51:5: error: unknown type name ‘pid_t’
 pid_t pid;
 ^
client.c: In function ‘main’:
client.c:62:5: error: unknown type name ‘pid_t’
 pid_t pid = getpid();
 ^
make: *** [client.o] Error 1
```

Any idea how to resolve this?

**Comment by silentbicycle** [comment]
`pid_t` is a type definition associated with getpid(). You didn't mention what platform you're on (Linux, BSD, OSX, something else?), but if you're on a Unix-ish OS you should have the man pages for the base system installed. If you run `man getpid` at the command line, it should bring up the man page (which is the primary documentation) for getpid, which will probably say:

```
#include <unistd.h>
```

near the top, by the type signatures for `getpid`. That's part of the Unix / C convention for saying that `unistd.h` defines that function and its related types.

It sounds like you're trying to build the client.c in my project, which [does have that included](https://github.com/silentbicycle/mqtt_demo/blob/master/client.c#L21). What platform are you on? That seems unusual.

**Comment by jsavage** [comment]
Hi Scott,
Sorry, should have said, Ubuntu 14.04. And yes this is building client.c
from your mqtt_demo
man getpid does indeed bring up that info but running getpid in the
terminal returns nothing I imagine that this is because it is a function
rather than a command.

#include <unistd.h> is present in your source file.

uname -a
Linux jsavage-U14 3.13.0-45-generic #74-Ubuntu SMP Tue Jan 13 19:36:28 UTC
2015 x86_64 x86_64 x86_64 GNU/Linux

---

To gain confidence in getpid() I successfully compiled and ran the
following snippit of code which I found online:
cat pid.c
#include <sys/types.h>
#include <unistd.h>
#include<stdio.h>

int main()
{
printf("process ID %d\n", getpid());
printf("parent process ID %d\n\n", getppid());
return 0;
}

Kind regards,
James

On 12 March 2015 at 01:30, Scott Vokes notifications@github.com wrote:

> pid_t is a type definition associated with getpid(). You didn't mention
> what platform you're on (Linux, BSD, OSX, something else?), but if you're
> on a Unix-ish OS you should have the man pages for the base system
> installed. If you run man getpid at the command line, it should bring up
> the man page (which is the primary documentation) for getpid, which will
> probably say:
> 
> #include <unistd.h>
> 
> near the top, by the type signatures for getpid. That's part of the Unix
> / C convention for saying that unistd.h defines that function and its
> related types.
> 
> It sounds like you're trying to build the client.c in my project, which
> [does have that included] [
> https://github.com/silentbicycle/mqtt_demo/blob/master/client.c#L21].
> What platform are you on? That seems unusual.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/silentbicycle/mqtt_demo/issues/1#issuecomment-78408197
> .

## 

<a href="skype:jdcsavage?call"><img src="
http://mystatus.skype.com/balloon/jdcsavage" style="border: none;"
width="150" height="60" alt="My status" /></a>
<br /><a href="http://www.skype.com/go/download">Get Skype</a> and call me
for free.<br /><br />

**Comment by dstitt** [comment]
uname -a
Linux dell6510 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux

I got compilation error about pid_t and found that in addition to the include for unistd.h, I also needed to add this:
#include <sys/types.h>
