### ISSUE TITLE
failed to build

### ISSUE THREAD

**Issue by JRGolf** [silentbicycle/mqtt_demo#2]
Hi. many thanks for this example.  I am having trouble building as follows:

make
cc -std=c99 -g -O3 -Wall    -c -o client.o client.c
cc -lmosquitto  client.o   -o client
client.o: In function `on_connect':
/home/jo/Documents/examples/silentbicycle/mqtt_demo/client.c:104: undefined reference to `mosquitto_subscribe'
/home/jo/Documents/examples/silentbicycle/mqtt_demo/client.c:105: undefined reference to `mosquitto_subscribe'
/home/jo/Documents/examples/silentbicycle/mqtt_demo/client.c:111: undefined reference to `mosquitto_subscribe'
/home/jo/Documents/examples/silentbicycle/mqtt_demo/client.c:112: undefined reference to `mosquitto_subscribe'

etc. etc.

I have installed mosquitto, mosquitto-clients, and libmosquitto on Ubuntu 16.04.lts and you file includes "mosquitto.h".  Please can you tell me what I have not done!  Thanks

**Comment by silentbicycle** [comment]
This looks like a packaging issue -- Ubuntu 16.04.lts has distinct libmosquitto0 and libmosquitto1 packages, and you may have the header associated with one but the other library installed. This example is from March 2014, so it won't reflect recent library interface changes.

Also, apt-based distributions such as Ubuntu and Debian usually put headers in secondary `-dev` packages, so installing those may be necessary. I'll add a note to this effect in the README.

**Comment by JRGolf** [comment]
I've uninstalled and reinstallled mosquitto, mosquitto-clients, libmosquitto-dev and this also gave me libmosquitto1.  I tried to install libmosquitto0 but was unable to locate package, so I think all should be ok, but I still have the same problem.

**Comment by silentbicycle** [comment]
I don't have an Ubuntu 16.04.lts system set up, but when I have time I'll see if I can reproduce your issue in a vagrant box.

**Comment by silentbicycle** [comment]
Using the `ubuntu/xenial64` Vagrant box, I was able to build after installing `make`, `clang`, `mosquitto`, `libmosquitto-dev`, and cloning the repo.

**Comment by mosbuma** [comment]
I had the same problem on ubuntu 16.04. Changing LDFLAGS to LDLIBS in the makefile fixed it for me....

**Comment by silentbicycle** [comment]
Note the following, from the README: 

NOTE: THIS EXAMPLE MAY BE OUT OF DATE!
It was written four years ago and the Mosquitto C library has had API changes. This example is no longer actively maintained (but pull requests or requests to take over maintainership are welcome).
